name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '52 18 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout self
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Checkout source tree
        uses: actions/checkout@v2
        with:
          repository: TurboWarp/scratch-gui
          path: scratch-gui
      - name: Build
        run: |
          cd scratch-gui
          npm ci
          NODE_ENV=production ROUTING_STYLE=hash npm run build
      - name: Patch
        run: python3 patch.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: scratch-gui/build
          single-commit: true
